# Generated by Django 4.1 on 2022-09-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_agora_app', '0003_remove_post_slug_alter_post_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_caption',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
