# Generated by Django 4.1 on 2022-09-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_agora_app', '0004_post_image_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=15, null=True),
        ),
    ]
