# Generated by Django 4.1 on 2022-09-06 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_agora_app', '0006_remove_comment_body_comment_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='description',
            new_name='body',
        ),
    ]
