# Generated by Django 4.1 on 2022-09-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_agora_app', '0007_rename_description_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
