# Generated by Django 4.1 on 2022-09-07 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_agora_app', '0008_alter_comment_body_alter_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='virtual_agora_app.quote'),
        ),
    ]
