# Generated by Django 4.1 on 2022-09-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_agora_app', '0010_philosopher_date_of_birth_philosopher_date_of_death_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='philosopher',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
