# Generated by Django 4.1 on 2022-09-11 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_agora_app', '0011_alter_philosopher_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='theme',
        ),
    ]
